import React from "react";
import { Navigate } from "react-router-dom";
import "../style/Output.css";
import Cart from "./Cart";


class Output extends React.Component {
    constructor(props) {
        super(props);

    }

    
    async addToCart(labels, imageLink,timestamp)
    {
        let response = await fetch("http://localhost:5000/add_products", {
            method: "POST",
            headers:{
                'Content-Type':'application/json'
            },
            body:JSON.stringify({
                createdBy: localStorage.getItem("username"),
                description: `Automaticly generated by the labels: ${labels[0]}, ${labels[1]}, ${labels[2]}`,
                imageLink: imageLink,
                timestamp: timestamp
            })
        })
        response = await response.json();
        return response.error;
    }

    render() {


        return (
            <div className="containerOutput">
                <img src="123"   id="image1"onClick={()=>{
                    let containerImages=document.getElementsByClassName("containerOutput")[0];
                    let labels=containerImages.getAttribute("labels");
                    let source=document.getElementById("image1").src;
                    this.addToCart(labels.split(" "),source,Date.now());
                    
                
                }} className="outputImage"></img>
                <img src="" id="image2" onClick={()=>{
                    let containerImages=document.getElementsByClassName("containerOutput")[0];
                    let labels=containerImages.getAttribute("labels");
                    let source=document.getElementById("image2").src;
                    this.addToCart(labels.split(" "),source,Date.now());
                    
                
                }}className="outputImage"></img>
                <img src="" id="image3" onClick={()=>{
                    let containerImages=document.getElementsByClassName("containerOutput")[0];
                    let labels=containerImages.getAttribute("labels");
                    let source=document.getElementById("image3").src;
                    this.addToCart(labels.split(" "),source,Date.now());
                    
                
                }} className="outputImage"></img>
                
            </div>


        );
    }


}

export default Output;